#! /usr/bin/env bash

# VPC var 

if [ -z "$1" ]; then
    echo "Argument not provided"
else 
    export VPC_ID="$1"
fi

# IGW var

if [ -z "$2" ]; then
    echo "Argument not provided"
else 
    export IGW_ID="$2"
fi

# Route table var
if [ -z "$3" ]; then
    echo "Argument not provided"
else 
    export RT_ID="$3"
fi

# Subnet var
if [ -z "$4" ]; then
    echo "Argument not provided"
else 
    export SUBNET_ID="$4"
fi



# Detach IGW

aws ec2-detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# Delete IGW

# aws ec2 delete-internet-gateway --internet

# Disassociate route table

aws ec2 disassociate-route-table --association-id $RT_ID


# Delete subnet

aws ec2 delete-subnet --subnet-id $SUBNET_ID

# Delete route table

aws ec2 delete-route-table --route-table-id $RT_ID

# Delete VPC

aws ec2 delete-vpc --vpc-id $VPC_ID
