#! /usr/bin/env bash

# Create new policy version

aws iam create-policy-version \
    --policy-arn arn:aws:iam::730335237557:policy/my-fun-policy \
    --policy-document "$(yq -o json policy.yaml)" \
    --set-as-default

# Attach polcy to user

# aws iam attach-user-policy \
# --policy-arn arn:aws:iam::730335237557:policy/my-fun-policy \
# --user-name Avi-Test-User